INSERT INTO MEMBERS (ID, USER_NAME, AGE)
VALUES (1, 'test-user01', 10);
INSERT INTO MEMBERS (ID, USER_NAME, AGE)
VALUES (2, 'test-user02', 20);
INSERT INTO MEMBERS (ID, USER_NAME, AGE)
VALUES (3, 'test-user03', 30);